gamma.3 - extensive corrections for compilation on FreeBSD

diff --git a/programs/clients/rservrd/Makefile.am b/programs/clients/rservrd/Makefile.am
--- a/programs/clients/rservrd/Makefile.am
+++ b/programs/clients/rservrd/Makefile.am
@@ -1,13 +1,13 @@
-STANDARD_INCLUDES=-I/usr/include -I/usr/local/include
+if LINK_LIBPTHREAD
+  USE_LIBPTHREAD=-lpthread
+endif
+
 ALL_INCLUDES=$(STANDARD_INCLUDES) -I$(srcdir)/../../.. -I$(srcdir)/../../../include/rservr -I$(srcdir)/../../../include
 AM_CPPFLAGS=-DENABLE_VIRT_ARRAY_ALL $(ALL_INCLUDES)
-AM_CXXFLAGS=-ansi -Wall
-AM_CFLAGS=-Wall
-AM_LDFLAGS=
 bin_PROGRAMS=rservrd
-rservrd_SOURCES=daemon-commands.c daemon-socket.c daemon.c interface.c rservrd.c commands/general.c commands/clients.c commands/control.c commands/netcntl.c daemon-commands.h daemon-socket.h daemon.h interface.h commands/include/commands-common.h commands/include/general.h commands/include/clients.h commands/include/control.h commands/include/netcntl.h
-rservrd_LDADD=-lpthread ../../../plugins/netcntl/librsvp-netcntl.la ../../../plugins/rqconfig/librsvp-rqconfig.la ../../../libs/client/librservr-client.la
-EXTRA_DIST=NOTICE
+rservrd_SOURCES=daemon-commands.c daemon-socket.c daemon.c interface.c rservrd.c commands/general.c commands/clients.c commands/control.c commands/netcntl.c
+rservrd_LDADD=$(STANDARD_LIBRARIES) $(USE_LIBPTHREAD) ../../../plugins/netcntl/librsvp-netcntl.la ../../../plugins/rqconfig/librsvp-rqconfig.la ../../../libs/client/librservr-client.la
+EXTRA_DIST=NOTICE daemon-commands.h daemon-socket.h daemon.h interface.h commands/include/commands-common.h commands/include/general.h commands/include/clients.h commands/include/control.h commands/include/netcntl.h
 
 RSERVRD=rservrd
 RSERVRD_TABLE=/tmp/$(RSERVRD)
@@ -15,12 +15,24 @@ RSERVRD_PERMISSION=6755
 
 install-exec-hook:
 	if [ "$$(id -u 2> /dev/null)" -eq 0 ]; then \
-	  if ! ( id $(RSERVRD) &> /dev/null ); then \
-	    ( groupadd $(RSERVRD) || true ) &> /dev/null; \
-	    if ! ( useradd -g $(RSERVRD) $(RSERVRD) &> /dev/null ); then \
-	      ( echo "{fail point 1}" && cat $(srcdir)/NOTICE && sleep 2 ) 1>&2 || true; \
-	    fi; \
-	  fi; \
+	  case "$$(uname)" in \
+	    "Linux"|"linux") \
+	      if ! id $(RSERVRD); then \
+	        groupadd $(RSERVRD) || true; \
+	        if ! useradd -g $(RSERVRD) -d $(RSERVRD_TABLE) $(RSERVRD); then \
+	          ( echo "{fail point 1[Linux]}" && cat $(srcdir)/NOTICE && sleep 2 ) 1>&2 || true; \
+	        fi; \
+	      fi; \
+	    ;; \
+	    "FreeBSD"|"freebsd") \
+	      if ! id $(RSERVRD); then \
+	        pw groupadd $(RSERVRD) || true; \
+	        if ! pw useradd $(RSERVRD) -g $(RSERVRD) -d $(RSERVRD_TABLE); then \
+	          ( echo "{fail point 1[FreeBSD]}" && cat $(srcdir)/NOTICE && sleep 2 ) 1>&2 || true; \
+	        fi; \
+	      fi; \
+	    ;; \
+	  esac; \
 	  if ! ( chown $(RSERVRD):$(RSERVRD) $(DESTDIR)$(bindir)/$(RSERVRD) &> /dev/null ) || \
 	     ! ( chmod $(RSERVRD_PERMISSION) $(DESTDIR)$(bindir)/$(RSERVRD) &> /dev/null ); then \
 	    ( echo "{fail point 2}" && cat $(srcdir)/NOTICE && sleep 2 ) 1>&2 || true; \
@@ -33,6 +45,14 @@ install-exec-hook:
 uninstall-hook:
 	if [ "$$(id -u 2> /dev/null)" -eq 0 ]; then \
 	  ( rm -rfv $(RSERVRD_TABLE) &> /dev/null ) || true; \
-	  ( userdel $(RSERVRD) &> /dev/null ) || true; \
-	  ( groupdel $(RSERVRD) &> /dev/null ) || true; \
+	  case "$$(uname)" in \
+	    "Linux"|"linux") \
+	      ( userdel $(RSERVRD) &> /dev/null ) || true; \
+	      ( groupdel $(RSERVRD) &> /dev/null ) || true; \
+	    ;; \
+	    "FreeBSD"|"freebsd") \
+	      ( pw userdel $(RSERVRD) &> /dev/null ) || true; \
+	      ( pw groupdel $(RSERVRD) &> /dev/null ) || true; \
+	    ;; \
+	  esac; \
 	fi;
diff --git a/programs/clients/rservrd/Makefile.in b/programs/clients/rservrd/Makefile.in
--- a/programs/clients/rservrd/Makefile.in
+++ b/programs/clients/rservrd/Makefile.in
@@ -49,7 +49,9 @@ am_rservrd_OBJECTS = daemon-commands.$(OBJEXT) daemon-socket.$(OBJEXT) \
 	general.$(OBJEXT) clients.$(OBJEXT) control.$(OBJEXT) \
 	netcntl.$(OBJEXT)
 rservrd_OBJECTS = $(am_rservrd_OBJECTS)
-rservrd_DEPENDENCIES = ../../../plugins/netcntl/librsvp-netcntl.la \
+am__DEPENDENCIES_1 =
+rservrd_DEPENDENCIES = $(am__DEPENDENCIES_1) \
+	../../../plugins/netcntl/librsvp-netcntl.la \
 	../../../plugins/rqconfig/librsvp-rqconfig.la \
 	../../../libs/client/librservr-client.la
 DEFAULT_INCLUDES = -I.@am__isrc@
@@ -89,30 +91,35 @@ CYGPATH_W = @CYGPATH_W@
 DEFS = @DEFS@
 DEPDIR = @DEPDIR@
 DSYMUTIL = @DSYMUTIL@
-ECHO = @ECHO@
+DUMPBIN = @DUMPBIN@
 ECHO_C = @ECHO_C@
 ECHO_N = @ECHO_N@
 ECHO_T = @ECHO_T@
 EGREP = @EGREP@
 EXEEXT = @EXEEXT@
-F77 = @F77@
-FFLAGS = @FFLAGS@
+FGREP = @FGREP@
 GREP = @GREP@
 INSTALL = @INSTALL@
 INSTALL_DATA = @INSTALL_DATA@
 INSTALL_PROGRAM = @INSTALL_PROGRAM@
 INSTALL_SCRIPT = @INSTALL_SCRIPT@
 INSTALL_STRIP_PROGRAM = @INSTALL_STRIP_PROGRAM@
+LD = @LD@
 LDFLAGS = @LDFLAGS@
 LIBOBJS = @LIBOBJS@
 LIBS = @LIBS@
 LIBTOOL = @LIBTOOL@
+LIPO = @LIPO@
 LN_S = @LN_S@
 LTLIBOBJS = @LTLIBOBJS@
 MAKEINFO = @MAKEINFO@
 MKDIR_P = @MKDIR_P@
+NM = @NM@
 NMEDIT = @NMEDIT@
+OBJDUMP = @OBJDUMP@
 OBJEXT = @OBJEXT@
+OTOOL = @OTOOL@
+OTOOL64 = @OTOOL64@
 PACKAGE = @PACKAGE@
 PACKAGE_BUGREPORT = @PACKAGE_BUGREPORT@
 PACKAGE_NAME = @PACKAGE_NAME@
@@ -133,7 +140,7 @@ abs_top_builddir = @abs_top_builddir@
 abs_top_srcdir = @abs_top_srcdir@
 ac_ct_CC = @ac_ct_CC@
 ac_ct_CXX = @ac_ct_CXX@
-ac_ct_F77 = @ac_ct_F77@
+ac_ct_DUMPBIN = @ac_ct_DUMPBIN@
 am__include = @am__include@
 am__leading_dot = @am__leading_dot@
 am__quote = @am__quote@
@@ -164,6 +171,7 @@ libdir = @libdir@
 libexecdir = @libexecdir@
 localedir = @localedir@
 localstatedir = @localstatedir@
+lt_ECHO = @lt_ECHO@
 mandir = @mandir@
 mkdir_p = @mkdir_p@
 oldincludedir = @oldincludedir@
@@ -179,15 +187,12 @@ target_alias = @target_alias@
 top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
-STANDARD_INCLUDES = -I/usr/include -I/usr/local/include
+@LINK_LIBPTHREAD_TRUE@USE_LIBPTHREAD = -lpthread
 ALL_INCLUDES = $(STANDARD_INCLUDES) -I$(srcdir)/../../.. -I$(srcdir)/../../../include/rservr -I$(srcdir)/../../../include
 AM_CPPFLAGS = -DENABLE_VIRT_ARRAY_ALL $(ALL_INCLUDES)
-AM_CXXFLAGS = -ansi -Wall
-AM_CFLAGS = -Wall
-AM_LDFLAGS = 
-rservrd_SOURCES = daemon-commands.c daemon-socket.c daemon.c interface.c rservrd.c commands/general.c commands/clients.c commands/control.c commands/netcntl.c daemon-commands.h daemon-socket.h daemon.h interface.h commands/include/commands-common.h commands/include/general.h commands/include/clients.h commands/include/control.h commands/include/netcntl.h
-rservrd_LDADD = -lpthread ../../../plugins/netcntl/librsvp-netcntl.la ../../../plugins/rqconfig/librsvp-rqconfig.la ../../../libs/client/librservr-client.la
-EXTRA_DIST = NOTICE
+rservrd_SOURCES = daemon-commands.c daemon-socket.c daemon.c interface.c rservrd.c commands/general.c commands/clients.c commands/control.c commands/netcntl.c
+rservrd_LDADD = $(STANDARD_LIBRARIES) $(USE_LIBPTHREAD) ../../../plugins/netcntl/librsvp-netcntl.la ../../../plugins/rqconfig/librsvp-rqconfig.la ../../../libs/client/librservr-client.la
+EXTRA_DIST = NOTICE daemon-commands.h daemon-socket.h daemon.h interface.h commands/include/commands-common.h commands/include/general.h commands/include/clients.h commands/include/control.h commands/include/netcntl.h
 RSERVRD = rservrd
 RSERVRD_TABLE = /tmp/$(RSERVRD)
 RSERVRD_PERMISSION = 6755
@@ -540,12 +545,24 @@ uninstall-am: uninstall-binPROGRAMS
 
 install-exec-hook:
 	if [ "$$(id -u 2> /dev/null)" -eq 0 ]; then \
-	  if ! ( id $(RSERVRD) &> /dev/null ); then \
-	    ( groupadd $(RSERVRD) || true ) &> /dev/null; \
-	    if ! ( useradd -g $(RSERVRD) $(RSERVRD) &> /dev/null ); then \
-	      ( echo "{fail point 1}" && cat $(srcdir)/NOTICE && sleep 2 ) 1>&2 || true; \
-	    fi; \
-	  fi; \
+	  case "$$(uname)" in \
+	    "Linux"|"linux") \
+	      if ! id $(RSERVRD); then \
+	        groupadd $(RSERVRD) || true; \
+	        if ! useradd -g $(RSERVRD) -d $(RSERVRD_TABLE) $(RSERVRD); then \
+	          ( echo "{fail point 1[Linux]}" && cat $(srcdir)/NOTICE && sleep 2 ) 1>&2 || true; \
+	        fi; \
+	      fi; \
+	    ;; \
+	    "FreeBSD"|"freebsd") \
+	      if ! id $(RSERVRD); then \
+	        pw groupadd $(RSERVRD) || true; \
+	        if ! pw useradd $(RSERVRD) -g $(RSERVRD) -d $(RSERVRD_TABLE); then \
+	          ( echo "{fail point 1[FreeBSD]}" && cat $(srcdir)/NOTICE && sleep 2 ) 1>&2 || true; \
+	        fi; \
+	      fi; \
+	    ;; \
+	  esac; \
 	  if ! ( chown $(RSERVRD):$(RSERVRD) $(DESTDIR)$(bindir)/$(RSERVRD) &> /dev/null ) || \
 	     ! ( chmod $(RSERVRD_PERMISSION) $(DESTDIR)$(bindir)/$(RSERVRD) &> /dev/null ); then \
 	    ( echo "{fail point 2}" && cat $(srcdir)/NOTICE && sleep 2 ) 1>&2 || true; \
@@ -557,8 +574,16 @@ install-exec-hook:
 uninstall-hook:
 	if [ "$$(id -u 2> /dev/null)" -eq 0 ]; then \
 	  ( rm -rfv $(RSERVRD_TABLE) &> /dev/null ) || true; \
-	  ( userdel $(RSERVRD) &> /dev/null ) || true; \
-	  ( groupdel $(RSERVRD) &> /dev/null ) || true; \
+	  case "$$(uname)" in \
+	    "Linux"|"linux") \
+	      ( userdel $(RSERVRD) &> /dev/null ) || true; \
+	      ( groupdel $(RSERVRD) &> /dev/null ) || true; \
+	    ;; \
+	    "FreeBSD"|"freebsd") \
+	      ( pw userdel $(RSERVRD) &> /dev/null ) || true; \
+	      ( pw groupdel $(RSERVRD) &> /dev/null ) || true; \
+	    ;; \
+	  esac; \
 	fi;
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
